---
title: "New parameter estimation"
author: "Ross Cunning"
date: "4/2/2018"
output: html_document
---

```{r setup, include=FALSE}
# Set kintr options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE)

# Load libraries
library(tidyverse)  # install.packages("tidyverse")
library(cowplot)  # install.packages("cowplot")

# Load R functions
sapply(list.files(path="R/", pattern="*", full.names = TRUE), FUN=source)
```

### kv: colony volume per unit biomass (L/C-mol^-1^)
```{r m3_Cmol, fig.width=7, fig.height=3}
# Data from:
# Jokiel PL, Morrissey JI (1986) Influence of size on primary production in the 
#   reef coral Pocillopora damicornis and the macroalga Acanthophora spicifera. 
#   Mar Biol 91:15–26

# Enter data from Table 1
df <- data_frame(
  radius.cm = c(2.1, 3.4, 4.0, 5.0, 8.2, 12.5),
  tissue.dry.wt.g = c(0.21, 1.68, 1.78, 4.60, 16.21, 34.66)
)

# Calculate colony volume (as a hemisphere) and convert biomass to Cmol
#   Assumes 41.4% carbon by weight (Schutter et al. 2010)
df <- df %>%
  mutate(vol.m3 = 2/3 * pi * (radius.cm / 100)^3,
         vol.L = vol.m3 * 1000,
         Cmol = tissue.dry.wt.g * 0.414 / 12.011)  # gBiomass * 0.414 gC/gBiomass * 1molC/12.011gC

# Plot volume as a function of biomass - fit linear and exponential
lin <- ggplot(df, aes(x=Cmol, y=vol.L)) + 
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE, formula=y~x-1) +
  labs(x="Coral biomass (C-mol)", y="Coral volume (L)") +
  theme_bw()

expo <- ggplot(df, aes(x=Cmol, y=vol.L)) + 
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE, formula=y~exp(x)) +
  labs(x="Coral biomass (C-mol)", y="Coral volume (L)") +
  theme_bw()

plot_grid(lin, expo)

# Calculate slope of linear fit
linmod <- lm(vol.L ~ Cmol - 1, data=df)
coef(linmod)

# Get coefficients of exponential model
expomod <- nls(vol.L ~ a * Cmol ^ b, start=c(a=1, b=1), trace=F, data=df)
#plot(vol.L ~ Cmol, data=df)
#with(df, lines(Cmol, coef(expomod)[1] * Cmol ^ coef(expomod)[2]))
coef(expomod)

```

From these data, we estimate the value for the parameter defining coral colony volume per unit biomass to be `r round(coef(linmod), 2)` L/Cmol if we use the linear fit. We could also use the (potentially better) exponential fit with coefficients a = `r round(coef(expomod)[1], 3)` and b = `r round(coef(expomod)[2], 3)`.